
tokens:
  $letter= "([a-z]|[A-Z])"
  $space= "( |\t|(\r?\n))+"
 
  grammar ="grammar"
  root ="root"
  link= "link"
  identifier:String ="{letter}({letter}|[0-9])*"
  quotedstring:String = '\"[^"]*\"'
  colon= ':'
  assign= '='
  dot= '.'
  lbracket ='\{'
  rbracket ='\}'
 
blanks:
 space= "{space}"


starts:
 start

productions:
start = 'grammar' 'colon' grammarDef+ 'root' 'colon' 'identifier' 'link' 'colon' linkDef+ {start_def}
      ;
      
grammarDef = 'identifier' 'assign' 'quotedstring'  {grammar_def}
           ;
 
linkDef = 'identifier' 'dot' 'identifier' 'assign' 'identifier' linkStart? linkVersion? {link_def} 
        ;
        
linkStart:String = 'dot' 'identifier' {linkStart_def}
          ;
          
linkVersion:String = 'lbracket' 'identifier' 'rbracket' {linkVersion_def}
            ;
