imports:

priorities:
not = 2 nonassoc
and = 1 left
or= 0 left


tokens: 
  $white = '[ \t\n\r]'

  val:boolean = 'true|false'
  or = '\|'     [or]
  and = '[&]'    [and]
  not = '!'     [not]
  open_brace = '\('
  close_brace = '\)'
  space = "{white}"
  letter:char = '.'

blanks:
  blk = "{white}"

starts:
  start

productions:
  start = expr
        ;

  expr:boolean = expr 'and' expr [and] {and}
        | expr 'or' expr   [or] {or}
        | 'not' expr    [not] {not}
        | 'open_brace' expr 'close_brace' {parenthesis} 
        | 'val' {value}
       ;
       