
tokens:
  
types:
  'letter':char
  'javaLetter':char
  word:void
  classDef:void
  'imports':void
  start:void
  startOut:void
  endOut:void
  methodStart:void
  'name':String
  'type':String
  
productions: